Первая попытка/Asm
pprettysimpple/first-term pull request #2
Opened 2020-07-07 21:31 UTC by pprettysimpple

2020-07-07 23:35 UTC, kt-cpp requested changes

2020-07-07 23:35 UTC, kt-cpp commented on asm/mul.asm
> +                call            add_long_short
[minor] Достаточно перед 85 строкой положить этот carry в [r8] т.к. никто не могу писать в эту память силу того, что мы идём по увеличению разрядов чисел

2020-09-04 06:57 UTC, pprettysimpple commented on asm/mul.asm
> +                call            add_long_short
понял, исправил

2020-09-20 22:59 UTC, kt-cpp approved these changes

2020-09-20 22:59 UTC, merged