Первая попытка / bigint-opt
pprettysimpple/first-term pull request #4
Opened 2020-07-10 03:25 UTC by pprettysimpple

2020-07-10 10:32 UTC, kt-cpp requested changes

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    const size_t MAX_SMALL = 8;
[minor] Вынеси внутрь соответсвующего класса и сделай `constexpr`

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    struct buff {
[minor] Почему бы не вынести этот класс в отдельный файл?

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.h
> +        size_t capacity, ref_counter;
[minor] Две переменные на на одной строке

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    struct buff {
А зачем вообще этот класс не хранит внутри `std::vector`, ибо по эффективности сейчс не лучше при этом обладает меньшим функционалом

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +vector::vector() : size_small_data(1u) {}
[minorъ Странно создавать не пустой вектор в дефолтном конструторе. А ещё ты будешь читать мусорную память из твоего едиснвтенного элемента

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        auto *new_p = static_cast<uint32_t*>(operator new [] (n * 4));
[note] Лучше избегать оператор new с []

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        auto *new_p = static_cast<uint32_t*>(operator new [] (n * 4));
Да и вообще лучше бы буффер выделял эти ресурсы

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +// buffer should be unique
[minor]  Вырази это через ассёрт

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        push_back_realloc(val);
Кажется тут забыли увеличить размер

2020-07-10 10:32 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +}
Что будет если `new_size < get_size()`?

2020-07-10 12:12 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +vector::vector() : size_small_data(1u) {}
size_small_data хранит в нижнем бите small\big, а в остальных size.
Для этого у меня написаны геттеры и сеттеры

2020-07-10 12:16 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +}
Я написал минимально необходимую для меня реализацию вектора и она не поддерживает ресайз на число меньшее size, потому что я никогда его так не использую.

2020-07-10 12:51 UTC, pprettysimpple commented on bigint-optimized/vector.h
> +    struct buff {
Если я похраню вектор, то у меня будет оверхед на size, потому что мне нужен свой для small_object.
И во внутренних функциях начнётся проблема вида: "А у кого спросить сейчас size?".
Я этого не хочу.

2020-07-10 13:21 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +}
Поставил assert как явное предусловие

2020-07-10 13:21 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +        push_back_realloc(val);
И правда забыл. Пофиксил

2020-07-10 13:21 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +// buffer should be unique
Сделал

2020-07-10 13:22 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +        auto *new_p = static_cast<uint32_t*>(operator new [] (n * 4));
И правда лучше бы буффер

2020-07-10 13:22 UTC, pprettysimpple commented on bigint-optimized/vector.h
> +        size_t capacity, ref_counter;
Пофиксил

2020-07-10 13:22 UTC, pprettysimpple commented on bigint-optimized/vector.h
> +    const size_t MAX_SMALL = 8;
Вроде сделал

2020-07-10 15:03 UTC, kt-cpp requested changes
Есть, что надо исправить.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.h
> +    static constexpr size_t MAX_SMALL = 8;
[minor] Кажется, что это поле всё-таки стоит сделать приватным.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        auto *new_p = static_cast<uint32_t*>(operator new [] (n * 4));
Тут ничего не изменилось.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +vector::vector() : size_small_data(1u) {}
Это не самый удачный способ оптимизировать размер объекта. `size_small_data` всё равно имеет большое число неиспользуемых битов. Такое лучше реализовывать с помощью двух полей (состояние и размер) с использованием bit field.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +vector::vector() : size_small_data(1u) {}
Название `size_small_data` не очень удачное, потому что в нем всё-таки сейчас хранится информация о статусе объекта [small/big].

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +        ++(buffer->ref_counter);
[note] Всё-таки было бы лучше выделить логику CoW в отдельный класс.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +vector::~vector() {
Помимо освобождения памяти необходимо вызывать деструкторы элементов.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    auto *new_p = static_cast<uint32_t *>(operator new[](4 * get_size()));
Вынеси всю работу с буфером в его класс. И да, этот `new` тоже может бросить.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +vector::~vector() {
Окей, я понял, у тебя вектор хранит только числа. Не супер, но сойдет.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/buff.h
> +struct buff {
Сделай, пожалуйста, этот класс нормально. Перенеси в него всю логику, связанную с ним.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +size_t vector::increase_capacity() const {
Очень полезная функция. Вызывается ровно один раз. При этом есть место, где используется похожая формула с `MAX_SMALL`.
Вынеси эту логику в класс с буфером.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    if (lhs.get_size() != rhs.get_size()) {
Здесь можно сравнить просто `size_small_data`.

2020-07-10 15:03 UTC, kt-cpp commented on bigint-optimized/buff.h
> +struct buff {
И давай заодно сделаешь нормальное название у класса.

2020-07-10 15:16 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +vector::vector() : size_small_data(1u) {}
"size_small_data всё равно имеет большое число неиспользуемых битов"
-неправда, один бит под small/big, а ВСЕ остальные под размер
-я не поддерживаю на 32 битной системе вектора размера больше чем `2^31 - 1`, это да, но больше проблем не вижу
"Название size_small_data не очень удачное"
-в нём хранится `data` об `size` и `small`, всё логично

2020-07-10 15:22 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +    auto *new_p = static_cast<uint32_t *>(operator new[](4 * get_size()));
Про `new`
`make_unique()` в любом случае будет иметь гарантии не лучше `strong`.
Если он и бросит, то это будет не критично.

2020-07-10 15:26 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +size_t vector::increase_capacity() const {
Убрал похожую формулу.

2020-07-10 15:27 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +    if (lhs.get_size() != rhs.get_size()) {
Нет, нельзя.
Если два объекта не совпадают по `small/big`, это не значит что они не равны.
Как-никак у меня есть функция `pop_back()`, которая может уменьшить размер большого объекта.

2020-07-10 15:36 UTC, pprettysimpple commented on bigint-optimized/buff.h
> +struct buff {
Я не могу перенести всю логику в буфер, он - неотъемлемая часть вектора.
Я думаю это будет ошибкой, потому что мне придётся хранить 2 "одинаковых" `size`, один для вектора, второй для буфера, я этого делать не хочу. Собственно я и не использовал вектор из-за такой проблемы.
Когда я `small`, я хочу знать свой `size`. То есть не хранить в юнионе поверх `small_data`.
А когда я `big`, я же ведь тоже хочу знать `size`, но вы мне говорите хранить его в `buffer`.
Структуру буфер я использую только для последовательного хранения вещей в юнионе.

2020-07-10 18:13 UTC, kt-cpp requested changes

2020-07-10 18:13 UTC, kt-cpp commented on bigint-optimized/shared_ptr_vector.h
> +    std::vector<uint32_t> &get();
[minor] Этот класс всё равно деталь реализации, можно было сделать просто член публичным

2020-07-10 18:13 UTC, kt-cpp commented on bigint-optimized/vector.cpp
> +    size_ = rhs.size_;
[minor] Инициализация членов

2020-08-31 17:48 UTC, pprettysimpple commented on bigint-optimized/shared_ptr_vector.h
> +    std::vector<uint32_t> &get();
сделал все его члены публичными

2020-08-31 17:50 UTC, pprettysimpple commented on bigint-optimized/vector.cpp
> +    size_ = rhs.size_;
поправил

2020-09-20 23:07 UTC, kt-cpp approved these changes

2020-09-20 23:07 UTC, merged